allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
lockfile: true
minimumReleaseAgeExclude:
  - '@angular-devkit/architect@0.2202.0'
  - '@angular-devkit/core@22.2.0'
  - '@angular-devkit/schematics@22.2.0'
  - '@angular/build@22.2.0'
  - '@angular/cli@22.2.0'
  - '@angular/common@22.2.0'
  - '@angular/compiler-cli@22.2.0'
  - '@angular/compiler@22.2.0'
  - '@angular/core@22.2.0'
  - '@angular/forms@22.2.0'
  - '@angular/platform-browser@22.2.0'
  - '@angular/router@22.2.0'
  - '@schematics/angular@22.2.0'
  - ng-packagr@22.2.1
